import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
    render() {
        return (
            <Html lang="ja">
                <Head>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link href="/style.css" rel="stylesheet" />
                </Head>
                <body>
                    <script>
                    </script>
                </body>
                <Main />
                <NextScript />
            </Html>
        )
    }
}


const themeInitializerScript = `( function() {
  ${ setInitial.toString() }
  setInitial();
})()`;

function setInitial() { // ローカルストレージから前回の設定を読み込み・適応
  const stored = window.localStorage.getItem('setting1');
  if(typeof stored === 'string') { // ローカルストレージは「文字列しか入れられない」ので注意
    if(stored === 'true') {
        document.getElementById('setting1').checked = true;
    } else {
        document.getElementById('setting1').checked = false;
    }
  }
  /*
  if(window.matchMedia('(min-width: 600px)').matches) { // 指定された文字列のオブジェクトを返す。if文内に入れれば、今回ならレスポンシブかどうかで処理を変えられる
    document.getElementById('setting1').checked = true; // すでに以前ユーザーが設定を変更していた場合、そこにチェックを入れる/外す
  }*/
}

export default MyDocument;